=== zhawei3636/MongoQuerier/src/main/java/com/bingdian/mapping/collection-relation.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema targetNamespace="bingdian" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified" attributeFormDefault="qualified">
    <xsd:element name="collections">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="collection">
                    <xsd:complexType>
                        <xsd:sequence>
                           <xsd:element ref="relation" />
                        </xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string" use="required" />
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="relation">
         <xsd:complexType>
             <xsd:sequence>
                 <xsd:element name="key" type="xsd:string" />
                 <xsd:element name="reference" type="xsd:string">
                     <xsd:complexType>
                         <xsd:attribute name="type" default="objectId">
                             <xsd:simpleType>
                                 <xsd:restriction base="xsd:NMTOKEN">
                                     <xsd:enumeration value="objectId" />
                                     <xsd:enumeration value="string" />
                                 </xsd:restriction>
                             </xsd:simpleType>
                         </xsd:attribute>
                     </xsd:complexType>
                 </xsd:element>
             </xsd:sequence>
         </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== zhawei3636/MongoQuerier/src/main/java/com/bingdian/mapping/collection-relation.xml
<?xml version="1.0"  encoding="utf-8" ?>

<collections xmlns="bingdian"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="collection-relation.xsd">

    <collection name="City">
        <relation>
            <key>cityId</key>
            <reference>City._id</reference>
        </relation>
        <relation>
            <key>cityId</key>
            <reference >City._id</reference>
        </relation>
    </collection>
</collections>
